// Generated by BUCKLESCRIPT VERSION 1.4.2 , PLEASE EDIT WITH CARE
'use strict';


function select(string, t) {
  return t.select(string);
}

function elements(t) {
  return t.elements();
}

function events(string, t) {
  return t.events(string, undefined);
}

exports.select   = select;
exports.elements = elements;
exports.events   = events;
/* No side effect */
