// Generated by BUCKLESCRIPT VERSION 1.4.2 , PLEASE EDIT WITH CARE
'use strict';

var Xstream = require("xstream");

function periodic(period) {
  return Xstream.default.periodic(period);
}

function singleton(x) {
  var array = /* array */[x];
  return Xstream.default.fromArray(array);
}

exports.periodic  = periodic;
exports.singleton = singleton;
/* xstream Not a pure module */
