// Generated by BUCKLESCRIPT VERSION 1.4.1 , PLEASE EDIT WITH CARE
'use strict';

var Vnode             = require("snabbdom/vnode");
var $atcycle$slashdom = require("@cycle/dom");
var $$Array           = require("bs-platform/lib/js/array");

function h(sel, $staropt$star, children) {
  var attrs = $staropt$star ? $staropt$star[0] : { };
  return Vnode(sel, {
              attrs: attrs
            }, $$Array.of_list(children), undefined, undefined);
}

function text(string) {
  return Vnode(undefined, { }, /* array */[], string, undefined);
}

function make_dom_driver(prim) {
  return $atcycle$slashdom.makeDOMDriver(prim);
}

var Source = 0;

exports.make_dom_driver = make_dom_driver;
exports.h               = h;
exports.text            = text;
exports.Source          = Source;
/* snabbdom/vnode Not a pure module */
