// Generated by BUCKLESCRIPT VERSION 1.4.2 , PLEASE EDIT WITH CARE
'use strict';

var Cycle_xstream_run = require("@cycle/xstream-run");

function run(main, drivers) {
  return Cycle_xstream_run.run(main, drivers);
}

exports.run = run;
/* @cycle/xstream-run Not a pure module */
