// Generated by BUCKLESCRIPT VERSION 1.4.1 , PLEASE EDIT WITH CARE
'use strict';


function incr(t) {
  return t + 1 | 0;
}

function decr(t) {
  return t - 1 | 0;
}

exports.incr = incr;
exports.decr = decr;
/* No side effect */
