// Generated by BUCKLESCRIPT VERSION 1.4.1 , PLEASE EDIT WITH CARE
'use strict';


function of_int(i) {
  return i;
}

function to_int(t) {
  return t;
}

function incr(t) {
  return t + 1 | 0;
}

function decr(t) {
  return t - 1 | 0;
}

exports.of_int = of_int;
exports.to_int = to_int;
exports.incr   = incr;
exports.decr   = decr;
/* No side effect */
