// Generated by BUCKLESCRIPT VERSION 1.4.2 , PLEASE EDIT WITH CARE
'use strict';

var Curry             = require("bs-platform/lib/js/curry");
var Cycle             = require("./cycle");
var Comment           = require("./comment");
var Cycle_dom         = require("./cycle_dom");
var Cycle_xstream_run = require("./cycle_xstream_run");
var Bulma             = require("style!bulma/css/bulma.css");

Cycle_xstream_run.run(Comment.main, {
      DOM: Curry._1(Cycle_dom.make_dom_driver, "#app")
    });

/*  Not a pure module */
