// Generated by BUCKLESCRIPT VERSION 1.4.1 , PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array");

var Options = /* module */[];

function make($staropt$star, $staropt$star$1, _) {
  var options = $staropt$star ? $staropt$star[0] : { };
  var locales = $staropt$star$1 ? $staropt$star$1[0] : /* [] */0;
  var match = locales ? /* tuple */[
      $$Array.of_list(locales),
      options
    ] : /* tuple */[
      undefined,
      undefined
    ];
  return new Intl.DateTimeFormat(match[0], match[1]);
}

exports.Options = Options;
exports.make    = make;
/* No side effect */
