// Generated by BUCKLESCRIPT VERSION 1.4.2 , PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives");

function make(year, month, date, hours, minutes, seconds, milliseconds, _) {
  if (year) {
    if (month) {
      var month$prime = month[0];
      var year$prime = year[0];
      if (date) {
        var date$prime = date[0];
        if (hours) {
          var hours$prime = hours[0];
          if (minutes) {
            var minutes$prime = minutes[0];
            if (seconds) {
              var seconds$prime = seconds[0];
              if (milliseconds) {
                return new Date(year$prime, month$prime, date$prime, hours$prime, minutes$prime, seconds$prime, milliseconds[0]);
              }
              else {
                return new Date(year$prime, month$prime, date$prime, hours$prime, minutes$prime, seconds$prime);
              }
            }
            else if (milliseconds) {
              return Pervasives.failwith("Invalid date");
            }
            else {
              return new Date(year$prime, month$prime, date$prime, hours$prime, minutes$prime);
            }
          }
          else if (seconds) {
            return Pervasives.failwith("Invalid date");
          }
          else if (milliseconds) {
            return Pervasives.failwith("Invalid date");
          }
          else {
            return new Date(year$prime, month$prime, date$prime, hours$prime);
          }
        }
        else if (minutes) {
          return Pervasives.failwith("Invalid date");
        }
        else if (seconds) {
          return Pervasives.failwith("Invalid date");
        }
        else if (milliseconds) {
          return Pervasives.failwith("Invalid date");
        }
        else {
          return new Date(year$prime, month$prime, date$prime);
        }
      }
      else if (hours) {
        return Pervasives.failwith("Invalid date");
      }
      else if (minutes) {
        return Pervasives.failwith("Invalid date");
      }
      else if (seconds) {
        return Pervasives.failwith("Invalid date");
      }
      else if (milliseconds) {
        return Pervasives.failwith("Invalid date");
      }
      else {
        return new Date(year$prime, month$prime);
      }
    }
    else {
      return Pervasives.failwith("Invalid date");
    }
  }
  else if (month) {
    return Pervasives.failwith("Invalid date");
  }
  else if (date) {
    return Pervasives.failwith("Invalid date");
  }
  else if (hours) {
    return Pervasives.failwith("Invalid date");
  }
  else if (minutes) {
    return Pervasives.failwith("Invalid date");
  }
  else if (seconds) {
    return Pervasives.failwith("Invalid date");
  }
  else if (milliseconds) {
    return Pervasives.failwith("Invalid date");
  }
  else {
    return new Date();
  }
}

function ymdhms(prim, prim$1, prim$2, prim$3, prim$4, prim$5) {
  return new Date(prim, prim$1, prim$2, prim$3, prim$4, prim$5);
}

exports.ymdhms = ymdhms;
exports.make   = make;
/* No side effect */
