// Generated by BUCKLESCRIPT VERSION 1.4.2 , PLEASE EDIT WITH CARE
'use strict';

var Xstream = require("xstream");

function combine2(a, b) {
  return Xstream.MemoryStream.combine(/* record */[
              /* a */a,
              /* b */b
            ]);
}

exports.combine2 = combine2;
/* xstream Not a pure module */
