// Generated by BUCKLESCRIPT VERSION 1.4.1 , PLEASE EDIT WITH CARE
'use strict';


var Element = 0;

var Event = 0;

var Html_element = 0;

var Html_input_element = 0;

var Node = 0;

exports.Element            = Element;
exports.Event              = Event;
exports.Html_element       = Html_element;
exports.Html_input_element = Html_input_element;
exports.Node               = Node;
/* No side effect */
