// Generated by BUCKLESCRIPT VERSION 1.4.1 , PLEASE EDIT WITH CARE
'use strict';

var Xstream = require("xstream");

function periodic(period) {
  return Xstream.default.periodic(period);
}

function singleton(x) {
  var array = /* array */[x];
  return Xstream.default.fromArray(array);
}

function remember(prim) {
  return prim.remember();
}

exports.periodic  = periodic;
exports.singleton = singleton;
exports.remember  = remember;
/* xstream Not a pure module */
